    (function () {
      var panel   = document.getElementById('talsuPanel');
      var overlay = document.getElementById('talsuOverlay');
      var openBtn = document.getElementById('talsuOpenBtn');
      var closeBtn= document.getElementById('talsuCloseBtn');
      function openMenu()  { panel.classList.add('open');    overlay.classList.add('show');    document.body.style.overflow='hidden'; }
      function closeMenu() { panel.classList.remove('open'); overlay.classList.remove('show'); document.body.style.overflow=''; }
      openBtn.addEventListener('click', openMenu);
      closeBtn.addEventListener('click', closeMenu);
      overlay.addEventListener('click', closeMenu);
      document.querySelectorAll('.talsu-menu-item').forEach(function(item){
        item.addEventListener('click', function(){ setTimeout(closeMenu,160); });
      });
      document.querySelectorAll('.talsu-nav-item').forEach(function(btn){
        btn.addEventListener('click', function(){
          document.querySelectorAll('.talsu-nav-item').forEach(function(n){ n.classList.remove('active'); });
          btn.classList.add('active');
        });
      });
    })();


  const CONSTITUTION = [
    {
      num: 'SEC 1',
      title: 'Name, Membership & Supremacy of the Constitution',
      content: `
        <div class="sec-label">Section 1.1 — Name of the Union</div>
        <p>The union shall be known and addressed as <strong>Tangaza Local Government Students Union (TALSU)</strong>.</p>

        <div class="sec-label">Section 1.2 — Membership</div>
        <p>Every Tangaza student of Sokoto state indigene shall be an automatic member of this union upon payment of his/her registration fees.</p>
        <ul>
          <li><strong>Newly registered students</strong> are to pay a sum of Three Hundred Naira (<strong>#300</strong>).</li>
          <li><strong>Already registered students</strong> are to pay a sum of Two Hundred Naira (<strong>#200</strong>) annually.</li>
        </ul>
        <p>Members shall enjoy all the privileges of membership including the right to vote and be voted into any office of the union except where otherwise stated in this constitution.</p>
        <p>Graduates of the Tangaza students members who are Sokoto indigene throughout the federation and abroad shall remain <strong>alumni members</strong>.</p>

        <div class="sec-label">Section 1.3 — Supremacy of the Constitution</div>
        <p>Without prejudice to the provision of the constitution of the Federal Republic of Nigeria and constitution of Nigeria and abroad universities, this constitution serves as a supreme code (guide) to the union's activities and shall be binding on all the members, committees, congress, faculty governors and executive council of the union.</p>
        <p>Any rule, regulations or actions inconsistent with its provision shall be <strong>null and void</strong>.</p>
      `
    },
    {
      num: 'SEC 2',
      title: 'Aims, Objectives & Activities of the Union',
      content: `
        <div class="sec-label">Section 2.1 — Aims and Objectives</div>
        <ol>
          <li>To promote and encourage studies in higher institutions of learning among the Tangaza students of Sokoto state indigenes.</li>
          <li>To foster the spirit of cooperation among members, to cooperate with other unions, and to provide forum for discussion of scientific, social and educational problems relevant to the development of the Tangaza students profession.</li>
          <li>To provide the needs and welfare of the members.</li>
          <li>To do all such things that are directly or indirectly conducive to the attainment of the above objectives.</li>
          <li>To promote among members a sense of honour, respect and dignity of both in behaviour and outlook — this will create a satisfaction and favourable impression of the professions.</li>
          <li>To participate in carrying out self-help and communal projects, especially those of Tangaza students' importance.</li>
        </ol>

        <div class="sec-label">Section 2.2 — Activities of the Union</div>
        <ol>
          <li>To organise annual Schools visitation within Tangaza Local Govt metropolis, which involves:
            <ul>
              <li>Grand carrier guidance and visitations to both Primary and secondary schools in Tangaza local govt, Sokoto state.</li>
              <li>Inter secondary school quiz, debate and essay writing competitions.</li>
            </ul>
          </li>
          <li>To organise an orientation programme for fresh students.</li>
          <li>To organise a tutorial faculty for fresh and returning students.</li>
          <li>To organise seminars and other events that may promote the interest of the union.</li>
          <li>To organise send forth ceremony for graduating members.</li>
        </ol>
      `
    },
    {
      num: 'SEC 3',
      title: 'Finance',
      content: `
        <ol>
          <li>Funds shall be generated by fund raising activities as long as they do not jeopardize the aims and objectives of the union.</li>
          <li>Funds may be generated from government parastatals, business establishments and ALUMNI members.</li>
          <li>Other sources such as donations, gifts etc. are welcomed.</li>
          <li>All members shall pay the annual dues of <strong>#200</strong> minus <strong>#100</strong> for the union I.D Card which is meant for the fresh students (irrespective of level).</li>
        </ol>
      `
    },
    {
      num: 'SEC 4',
      title: 'Affiliation & Relationship with Other Unions',
      content: `
        <div class="sec-label">Section 4.1 — Affiliations</div>
        <ol>
          <li>Sokoto State Students Union (SOSSA)</li>
          <li>Sokoto State University Students' Union</li>
          <li>Students' Union (SU)</li>
          <li>Other affiliates of the three above</li>
        </ol>

        <div class="sec-label">Section 4.2 — Relationship with Other Unions</div>
        <p>The union shall co-exist with other recognised unions/Unions operating within and outside the campus.</p>
      `
    },
    {
      num: 'SEC 5',
      title: 'Organs of the Union',
      content: `
        <p>The union shall consist of three major bodies that will run the union's activities:</p>
        <ul>
          <li><strong>The Congress</strong></li>
          <li><strong>The Faculty Governors</strong></li>
          <li><strong>The Executive Council</strong></li>
        </ul>

        <div class="sec-label">Section 5.1 — Functions of the Congress</div>
        <ol>
          <li>Shall be the supreme decision body of the Union.</li>
          <li>Each Faculty shall nominate their own governor and notify the new executive council at most 30 days after their inauguration.</li>
          <li>Shall participate in all activities of the union (except where stipulated in the constitution e.g. specific function(s) of a particular body).</li>
          <li>All resolutions reached by the executive council and/or Faculty governors shall be subject to ratification by the congress.</li>
          <li>Shall nominate caretakers/nomination committee among the Faculty governors.</li>
          <li>All officers must submit an updated report of their activities during their tenureship to the congress (to be presented by either the president or secretary general).</li>
          <li>Congress in a particular Faculty has the power to change their Faculty governor if seen not performing his/her functions.</li>
          <li>Shall organise themselves and call for a meeting if the EXCO and Faculty governors fail to perform their duties; in such situation, a 400, 500 or 600 level member present shall chair such meeting(s) and any decision(s) taken during such meeting shall be binding on all members.</li>
        </ol>

        <div class="sec-label">Section 5.2 — Functions of the Faculty Governors</div>
        <ol>
          <li>Only active member of the union's activities shall be nominated as the Faculty governor.</li>
          <li>There shall be one nominee from each Faculty.</li>
          <li>Shall assist the EXCO in carrying out their responsibilities.</li>
          <li>Shall ensure that members from their respective Faculties attend congress meetings and other union's activities through adequate publicity and reminder.</li>
          <li>Shall take note of habitual absentees from his/her Faculty members.</li>
          <li>Shall compile all complaints from his/her members and forward them to the president for consideration through the assistant secretary general.</li>
          <li>Shall ensure that all complaints passed are treated accordingly.</li>
          <li>Shall collect annual fees in their respective Faculties and channel them to the treasurer/financial secretary.</li>
          <li>They may be consulted in all major issues of the union prior to congress meeting.</li>
          <li>Shall serve as the disciplinary committee legislative arm of the union.</li>
          <li>EXCO shall not be nominated as a Faculty governor.</li>
          <li>May be changed by his/her Faculty members if seen not performing his/her duties.</li>
          <li>Shall cease to exist immediately after inauguration of the new EXCO during the send forth ceremony.</li>
          <li>Faculty governor(s) may have second term if nominated again by his/her Faculty members.</li>
        </ol>

        <div class="sec-label">Section 5.3 — Executive Council</div>
        <p>The executive council of the union shall consist of the following:</p>
        <ol>
          <li>President</li>
          <li>Vice President</li>
          <li>Secretary General</li>
          <li>Financial Secretary</li>
          <li>Treasurer</li>
          <li>Welfare Director</li>
          <li>Public Relation Officer (PRO I)</li>
          <li>Public Relation Officer (PRO II)</li>
          <li>Organising Secretary</li>
        </ol>

        <div class="sec-label">Section 5.4 — Duties of the Executive Council</div>

        <div class="officer-card">
          <div class="officer-title">1. The President</div>
          <ol>
            <li>Shall be called president and shall be the chief executive of the union.</li>
            <li>Shall provide over all meetings and regulate all activities of the union except where it is stipulated in this constitution.</li>
            <li>Shall in consultation with the secretary general summon all congress and executive meetings.</li>
            <li>Shall be signatory to the union's account.</li>
            <li>Shall forward his/her plan of activities and expected expenditures to the Faculty governors and/or congress for consideration.</li>
            <li>Shall call for a vote in matters affecting the union where a consensus cannot or seems not to be reached.</li>
            <li>Shall demand quarterly report from financial secretary.</li>
            <li>Shall submit a written report of his/her activities on behalf of the union during his/her year in office as well as recommendations to the congress. In the event of resignation or impeachment due to gross misconduct, shall hand over all the union's properties to the Faculty governors.</li>
          </ol>
        </div>

        <div class="officer-card">
          <div class="officer-title">2. The Vice President</div>
          <ol>
            <li>Shall deputise the president during his/her absence.</li>
            <li>Shall take other duties assigned to him/her by the president or congress.</li>
            <li>Shall assist the president in general matters.</li>
            <li>Shall perform the duties assigned to him/her by the president.</li>
          </ol>
        </div>

        <div class="officer-card">
          <div class="officer-title">3. Secretary General</div>
          <ol>
            <li>Shall be the head of the secretariat.</li>
            <li>Shall keep records of the union's minutes, stationaries, books, computers, banners, public amplifiers, microphones etc.</li>
            <li>Shall in consultation with the EXCO draw up the agenda for congress meetings.</li>
            <li>Shall in consultation with the president draw up the agenda for EXCO and/or congress meetings.</li>
            <li>Shall supervise and control the day-to-day activities of the secretariat.</li>
            <li>Shall compile and update the list of all members of the union.</li>
            <li>Shall maintain the log book of the union and take note of habitual absence to the union's activities and meetings.</li>
            <li>Shall compile a sessional report on the activities of the union for approval of the EXCO's prior to its presentation to congress.</li>
            <li>In the event of resignation or impeachment due to gross misconduct, shall hand over all the union's properties to the Faculty governors.</li>
          </ol>
        </div>

        <div class="officer-card">
          <div class="officer-title">4. Financial Secretary</div>
          <ol>
            <li>Shall be the head of any financial committee.</li>
            <li>Shall receive the amount of all the union's money and financial transactions to the union and acknowledge such receipt to the secretary general.</li>
            <li>Shall be co-signatory to the union's account.</li>
            <li>Shall form a financial committee which shall be endorsed by the EXCO.</li>
            <li>Shall submit quarterly financial report to the congress.</li>
            <li>Shall explore a decent possible avenue for raising funds for the union.</li>
            <li>Shall ensure that all members pay their annual dues.</li>
          </ol>
        </div>

        <div class="officer-card">
          <div class="officer-title">5. Treasurer</div>
          <ol>
            <li>Shall be co-signatory to the union's account.</li>
            <li>Shall pay all authorized bills received by the union to the bank account before 24 hours.</li>
            <li>Shall liaise with the financial secretary and bank on all union's money that exceed ₦5,000.00 within 24 hours except on weekends and public holidays.</li>
          </ol>
        </div>

        <div class="officer-card">
          <div class="officer-title">6. Public Relation Officer (PRO I)</div>
          <ol>
            <li>Shall be the chairperson of the publicity committee.</li>
            <li>Shall be responsible for the printing jobs in consultations with the secretary general.</li>
            <li>Shall provide the appropriate link between the union and its associate through appropriate channel.</li>
            <li>Shall carry out such duties assigned to him/her by the president.</li>
          </ol>
        </div>

        <div class="officer-card">
          <div class="officer-title">7. Public Relation Officer (PRO II)</div>
          <ol>
            <li>Shall assist public relation officer I in discharging his/her duties.</li>
            <li>Shall carry out any other duties assigned to him/her by the president.</li>
          </ol>
        </div>

        <div class="officer-card">
          <div class="officer-title">8. Organising Secretary</div>
          <ol>
            <li>Shall be the chairman of the social committee.</li>
            <li>Shall be responsible for organising and coordinating all social functions of the union, such as sports, quiz and debate among members and other unions.</li>
            <li>Shall ensure that all venues for such occasions are well arranged before the scheduled time.</li>
            <li>Perform other duties assigned to him/her by the president.</li>
          </ol>
        </div>

        <div class="officer-card">
          <div class="officer-title">9. Welfare Director</div>
          <ol>
            <li>Shall be the chairman of the welfare committee.</li>
            <li>Shall be responsible for provision of all welfare facilities of the union, such as sports, quiz and debate among members and other unions.</li>
            <li>Perform other duties assigned to him/her by the president.</li>
          </ol>
        </div>
      `
    },
    {
      num: 'SEC 6',
      title: 'Committees',
      content: `
        <div class="sec-label">Section 6.1.1 — Nomination Committee</div>
        <ol>
          <li>Shall comprise of seven members each from each faculties, appointed by the congress; at least two must be finalists who shall be chairman and secretary while the remaining five, from any level, shall remain members of the committee.</li>
          <li>Shall comprise strictly students members of the union.</li>
          <li>Shall receive all properties of the union from all officers at most three days after their appointment.</li>
          <li>Shall arrange meeting with stakeholders and carry out nomination activities.</li>
          <li>Shall ensure that members to be nominated fulfil all nomination requirements stated in Section 7 subsection 7.3 and Section 3 subsection 1 of this constitution.</li>
          <li>Faculty governor(s) may be nominated as EXCO provided he/she is approved by his/her faculty members and fulfilled all the nomination laws.</li>
          <li>Any nominated faculty governor shall not pirate him/herself as faculty governor again and the position remains vacant for another nomination by the faculty member involved.</li>
          <li>Shall arrange and co-ordinate inauguration of the new EXCOS.</li>
          <li>Shall be dissolved immediately after inauguration of the new EXCOS.</li>
        </ol>

        <div class="sec-label">Section 6.1.2 — Caretaker Committee</div>
        <p>In case the election cannot hold, the caretaker committee shall be appointed. It shall comprise of 5 members among which at least two shall be finalists who shall act as chairman and secretary while the remaining three that may come from any level shall be members of the committee.</p>
        <p>The chairman of the committee shall act as president while other offices shall be distributed among the members of committee.</p>
        <p>Shall be dissolved by nominating/electoral committee a week before election.</p>

        <div class="sec-label">Section 6.2 — Fund Raising Committee</div>
        <ol>
          <li>Shall be headed by the financial secretary of the union.</li>
          <li>Shall comprise at most five members.</li>
          <li>Shall generate funds from government parastatals, business establishments, alumni members, students and other avenues that will not disrupt the image of the union.</li>
          <li>Shall be accountable to the congress and be ad-hoc, and be dissolved after the discharge of its specific functions.</li>
        </ol>

        <div class="sec-label">Section 6.3 — Other Committees</div>
        <p>These are committees set up by the Executive Council of the union when the need arise especially during annual visitation to some schools:</p>
        <ul>
          <li>Central Working Committee</li>
          <li>Education and Research Committee</li>
          <li>Orientation Committee</li>
          <li>Carrier Guidance and Visitation Committee</li>
          <li>Transport Committee</li>
          <li>Publicity Committee</li>
          <li>Refreshment Committee</li>
        </ul>

        <div class="sub-heading">Central Working Committee</div>
        <ol>
          <li>Shall consist of two members from each of other committees and shall appoint among themselves the chairman and secretary, while other chairmen/chairperson and secretaries of various committees are members of this committee.</li>
          <li>Shall make budget proposal for the programme based on proposals from various committees.</li>
          <li>Shall ensure implementation of all programmes and activities featuring during the week.</li>
          <li>Shall ensure prompt disbursement of funds to all committees and ensure prudent utilization of such by those concerned.</li>
          <li>To coordinate the activities of various committees and provide logistic support where necessary.</li>
          <li>Shall prepare a comprehensive report to the EXCOs at the end of the programme based on the reports received from various committees.</li>
          <li>Shall release a communiqué at the end of the programme.</li>
        </ol>

        <div class="sub-heading">Education and Research Committee</div>
        <ol>
          <li>Shall organise quiz, debate or essay writing competitions among secondary schools during the programme.</li>
          <li>Shall state the prizes to be given and their costs.</li>
          <li>Shall inform the school concerned at the reasonable time (2–3 weeks to the date of the competition).</li>
          <li>Shall provide the avenue for the programme.</li>
          <li>Shall frequently conduct tutorial for students.</li>
        </ol>

        <div class="sub-heading">Orientation Committee</div>
        <ol>
          <li>Shall coordinate orientation programme for fresh students.</li>
          <li>Shall adequately communicate with the new students before the date of the programme.</li>
          <li>Shall provide the venue for the programme.</li>
          <li>Shall carry out other duties assigned to them by the president.</li>
        </ol>

        <div class="sub-heading">Carrier Guidance and Visitation Committee</div>
        <ol>
          <li>Shall provide place (schools) to be visited in the state and arrange with authorities concerned as soon as possible.</li>
          <li>Shall inform the schools concerned at the right time (at least 1–2 weeks before the programme).</li>
          <li>Shall arrange for all items needed.</li>
          <li>Shall organise and conduct carrier talk to the secondary school concerned.</li>
        </ol>

        <div class="sub-heading">Transport Committee</div>
        <ol>
          <li>Shall consult EXCOs on where to source vehicles for transportation.</li>
          <li>Shall ensure that all the buses/cars to be used during each event are available before the take-off time.</li>
          <li>Shall coordinate transportation activities including duelling of the buses/cars and driver's wages throughout the Programme.</li>
        </ol>

        <div class="sub-heading">Publicity Committee</div>
        <ol>
          <li>Shall produce invitation posters and handbills for publicity of the programme.</li>
          <li>Shall make arrangement for photograph during each event.</li>
          <li>Shall give adequate publicity of the programme within and outside the university.</li>
          <li>Shall make sure that the information about the programme is in wide circulation at least 10 days prior to the programme.</li>
          <li>Shall invite the media in every activities of the programme (if affordable).</li>
        </ol>

        <div class="sub-heading">Refreshment Committee</div>
        <ul>
          <li>Shall give estimate of the cost of each refreshment of each event.</li>
          <li>Shall provide the refreshment at all events during the programme.</li>
          <li>Shall give a comprehensive report to the EXCOs of the expenditures after the programme.</li>
        </ul>
      `
    },
    {
      num: 'SEC 7',
      title: 'Tenureship & Nomination Guidelines',
      content: `
        <div class="sec-label">Section 7.1 — Tenureship</div>
        <ol>
          <li>All officers of the executive council shall hold office for one year (academic session). All officers of the caretaker committee shall be dissolved after discharge of specific functions, that is to hold office from the dissolution of the EXCOS to the inauguration of the new EXCOS (at most 30 days). Other committees stands dissolved after inauguration of the new EXCOS including the faculty governors.</li>
          <li>Any officer who wishes to resign shall notify the faculty governor of his/her faculty in written to the congress via the EXCO for acceptance or rejection.</li>
          <li>Any office rendered vacant shall be filled by way of another nomination by the congress within 2 weeks.</li>
        </ol>

        <div class="sec-label">Section 7.2 — General Guidelines for Nomination</div>
        <ol>
          <li>Each of the members to be nominated must have spent at least one academic session in the University (UDUS).</li>
          <li>A minimum of <strong>75% attendance</strong> of all the congress meeting held that session is a prerequisite for all nominees to be nominated into any office.</li>
          <li>Member must have updated all his/her financial obligations stated in section 3.1, roman figure 2 and 5 of this constitution.</li>
          <li>Nomination shall be by balloting, where each member is given a chance to nominate among them a person to serve as an EXCO in a particular office.</li>
          <li>In case of deadlock, the nomination committee shall decide the nominee based on the participation of the nominees to the union's activities.</li>
          <li>Any officer(s) impeached as a result of gross misconduct is/are not eligible to be nominated in any post again in the union.</li>
          <li>Nominees shall be announced at a meeting at least at most 5 days before the election day.</li>
          <li>Newly nominated members shall be sworn-in during the send forth ceremony of the graduating members.</li>
        </ol>

        <div class="sec-label">Section 7.3 — Guidelines for Nominating EXCO from Various Levels</div>
        <ol>
          <li><strong>President, Secretary General, Vice President</strong> shall be from 500 level (in case of 6-year course), 400 level (in case of 5-year course), and 400 level (in case of 4-year courses).</li>
          <li><strong>Treasurer</strong> shall be a female.</li>
          <li><strong>Public Relation Officer I</strong> shall be from main campus.</li>
          <li><strong>Public Relation Officer II</strong> shall be from City campus.</li>
        </ol>
        <div class="nb">NB: Nomination committee may decide the nominee in each of the offices in case of deadlock, provided that it is for the betterment of the union.</div>
      `
    },
    {
      num: 'SEC 8',
      title: 'Meetings',
      content: `
        <div class="sec-label">Section 8.1 — Congress Meetings</div>
        <ol>
          <li>There shall be at least three (3) congress meetings per academic session.</li>
          <li>Notice of meetings shall be in wide circulation for at least 48 hours prior to such meetings, except in emergency cases.</li>
          <li>After 30 minutes of the scheduled time of any congress meeting, such meeting shall commence regardless of whether a quorum is found or not.</li>
          <li>Decisions and resolutions taken at such meetings shall be binding on all members.</li>
          <li>Any decision(s) involving constitutional matters shall only be taken at congress meetings.</li>
          <li>Congress meetings shall last in not more than three (3) hours; as such adjournment of the meeting may be called by the congress if it exceeded 3 hours.</li>
        </ol>

        <div class="sec-label">Section 8.2 — Emergency Meetings</div>
        <ol>
          <li>May be called by the EXCOS or demand by the faculty governors or congress.</li>
          <li>The president shall chair such meetings; if the meetings are not called by the EXCOS, then the chairman of the faculty governors shall chair the meetings.</li>
        </ol>

        <div class="sec-label">Section 8.3 — Executive Council Meetings</div>
        <ol>
          <li>EXCOS shall meet from time to time to discuss issues concerning the union.</li>
          <li>Two-third majority of the EXCO members shall be required to form a quorum, or number present after an hour of the scheduled time.</li>
          <li>A simple majority on any issue shall be decided upon at such meetings.</li>
          <li>Any executive member who fails to attend any of the executive meetings twice concurrently without prior notice to the secretary general, he/she shall be suspended, and such action shall be communicated to the faculty governors and congress for necessary action.</li>
          <li>If he/she becomes a habitual absentee (i.e. 3 executive meetings) without prior notice to the secretary general, then his/her impeachment shall be effected.</li>
        </ol>

        <div class="sec-label">Section 8.4 — Faculty Governor's Meetings</div>
        <ol>
          <li>Faculty governors shall meet and nominate among themselves, a chairman and secretary.</li>
          <li>The head of the faculty governors shall be from highest level of study.</li>
          <li>Faculty governors shall meet to discuss issues concerning the union when the need arise.</li>
        </ol>

        <div class="sec-label">Section 8.5 — Attendance During Congress Meetings</div>
        <ol>
          <li>There shall be an attendance maintained by the union which shall be signed by the members in attendance.</li>
          <li>Those unable to attend should communicate to the secretary general through their respective faculty governors in written before commencement of the meeting.</li>
          <li>Any member from the senior faculty without <strong>75% attendance</strong> shall not be included in the union's send forth/graduation ceremony (except with a strong and authentic reason).</li>
        </ol>

        <div class="sec-label">Section 8.6 — Conducts During the Meetings</div>
        <ol>
          <li>Meetings shall be conducted under peaceful atmosphere.</li>
          <li>A chief whip (400, 500 or 600 level member) shall be appointed by the presiding officer before the commencement of the meeting.</li>
          <li>The chief whip shall be given 2–3 minutes to read the conducts of the meetings and mode of address stated in the constitution (sec. 8.6 and 8.7).</li>
          <li>Agenda shall be strictly adhered to.</li>
          <li>Medium of communication shall be English language only.</li>
          <li>Member(s) wishing to leave the meeting venue before adjournment shall do so by the permission of the presiding officer through the chief whip; failure to do so will result in striking-off his/her name from the attendance list of that particular meeting by the secretary general.</li>
          <li>Minutes of the last meeting shall be read and adopted before the commencement of every meeting (EXCO/congress/faculty governors).</li>
          <li>Any member wishing to speak shall indicate his/her hand and do so only by permission of the presiding officer.</li>
          <li>Side discussion, reading of papers or any other thing as to distract attention of the house or disturb the progress of the meeting shall not be condoned.</li>
          <li>All mobile phones shall be switched off or put on silent mode.</li>
          <li>No foul language or abusive words shall be used on any member, and if accidentally happened the person(s) involved must apologise there and then before proceeding of the meeting; if not the person shall leave the house and face disciplinary committee.</li>
          <li>Member(s) are not allowed to bring any visitor to the meeting except on special invitation from the union.</li>
          <li>Any member(s) under the influence of drugs and drugs like substances shall stay clear off of the meeting. Such an individual shall also face the disciplinary committee, and if he/she is a member of the exco or faculty governors, it may earn him/her impeachment.</li>
        </ol>

        <div class="sec-label">Section 8.7 — Mode of Address</div>
        <ol>
          <li>Any congressman/congress lady permitted to speak shall stand up, address the house and shall mention his/her name including department, and level of study except the presiding officer (an EXCO shall mention his/her position likewise the faculty governors).</li>
          <li>Any member shall address the congress as <strong>"Mr President, the congress…"</strong></li>
        </ol>

        <div class="sec-label">Section 8.8 — Motions</div>
        <ol>
          <li>All motions must be seconded and may be subjected to amendments.</li>
          <li>No motion shall be allowed to lie after they have been seconded and shall be passed in, if there are no counter motions or voted for or otherwise.</li>
          <li>In case of counter motions, sponsors of both motions shall be given 3 minutes each within which to defend such motions before voting.</li>
          <li>Both the mover and counter of the motion shall leave the congress meeting for a while before voting takes place.</li>
          <li>The presiding officer has the power to overrule any motion if it is not for the progress of the meeting or betterment of the union even before it is disclosed.</li>
        </ol>

        <div class="sec-label">Section 8.9 — Expressions to be Noted During Meetings</div>
        <ol>
          <li><strong>Constitutional observations:</strong> Shall top all proceedings and that part of the constitution must be cited and read for necessary action.</li>
          <li><strong>Point of order:</strong> Once raised, stops all proceedings until note of it is taken.</li>
          <li><strong>Point of correction:</strong> Once raised, stops all the proceeding until note of it is taken.</li>
          <li><strong>Point of observation:</strong> Once raised, stops all proceedings until note of it is taken.</li>
          <li><strong>Vital information:</strong> Vital information is written down and passed on to the presiding officer through the chief whip.</li>
        </ol>
      `
    },
    {
      num: 'SEC 9',
      title: 'Oath of Office',
      content: `
        <p>Before any officer resumes duty after been elected/nominated, he/she shall take oath of allegiance, to be administered by patron or staff adviser of the union. The oath reads:</p>
        <div class="nb">
          I ________________________________ do solemnly swear that, I will be faithful and bear true allegiance to Tangaza local govt Students union (TALSU), Sokoto State.<br><br>
          I will make sure that, I discharge my duties to the best of my abilities, and in accordance with the provision of (TALSU's) constitution, and in the interest and sincerity of its members.<br><br>
          I shall not allow my personal interest to influence my official decision, and I shall devote myself to the service and well-being of its members, so help me Allah.
        </div>
      `
    },
    {
      num: 'SEC 10',
      title: 'Patrons & Staff Advisers',
      content: `
        <p>Shall be persons of high repute who can give moral, academic and financial support to the union.</p>

        <div class="sec-label">Section 10.2 — Patrons</div>
        <ol>
          <li>Hon. Chairman of Tangaza local govt, Sokoto State</li>
          <li>District head of Tangaza</li>
          <li>District head of Gidan Madi</li>
          <li>District head of Gwangwano</li>
        </ol>

        <div class="sec-label">Section 10.3 — Staff Advisers</div>
        <ol>
          <li>Prof. Aminu Mode (Dean of Students Affairs)</li>
          <li>Mal. Ahmad Muhammad Tangaza (Lecturer; Medical Laboratory Science, UDUS)</li>
          <li>Alh. Adamu Umar (Wamakko local govt secretary)</li>
          <li>Aminu Umar G/Madi (Engineering Staff at SSU)</li>
          <li>Mal. Kaseem (Lecturer at Federal School of Nursing)</li>
          <li>Other staff advisers may be suggested by the EXCO from time to time.</li>
        </ol>
      `
    },
    {
      num: 'SEC 11',
      title: 'Interpretation, Adoption & Amendment',
      content: `
        <div class="sec-label">Section 11.1 — Interpretation of the Constitution</div>
        <ol>
          <li>The chairman constitution review committee shall be the chief interpreter of any part of this constitution that is not clear to congress.</li>
          <li>The secretary constitution review committee shall interpret the constitution in the absence of the chairman.</li>
          <li>Member(s) of the constitution review committee present shall interpret the constitution in the absence of the chairman and secretary.</li>
          <li>The presiding officer shall interpret the constitution in the absence of any member of the constitution review committee.</li>
        </ol>
        <div class="nb">NB: Critical issues shall be directed to the staff advisers for appropriate suggestions.</div>

        <div class="sec-label">Section 11.2 — Adoption of the Constitution</div>
        <p>This document (TALSU's CONSTITUTION) comes into effect from the date it is adopted by the congress of the union. Once adopted, all its provisions stands and shall be binding on all members.</p>

        <div class="sec-label">Section 11.3 — Amendment of the Constitution</div>
        <ol>
          <li>This constitution shall be due for amendment/review after five years (if deemed necessary) from the date of its adoption by the congress.</li>
          <li>In the event of its amendment, constitution review committee shall be set up by the congress, consisting of the chairman and secretary from different faculties (500–600 level), then four members from other levels.</li>
        </ol>

        <div class="sec-label">Section 11.4 — Constitution Drafting Committee</div>
        <p>This constitution was drafted by the constitution drafting committee set up by the congress of the union in the year (2017/2018 academic session).</p>
        <table>
          <thead>
            <tr>
              <th>S/N</th>
              <th>Name</th>
              <th>Level</th>
              <th>Rank</th>
            </tr>
          </thead>
          <tbody>
            <tr><td>1</td><td>Garba Abdullahi M.</td><td>500</td><td>Chairman</td></tr>
            <tr><td>2</td><td>Auwal M. Bello</td><td>300</td><td>Secretary</td></tr>
            <tr><td>3</td><td>Ibrahim S. Umar</td><td>300</td><td>Member</td></tr>
            <tr><td>4</td><td>Haliru Muhammad</td><td>200</td><td>Member</td></tr>
            <tr><td>5</td><td>Usman Garba</td><td>200</td><td>Member</td></tr>
            <tr><td>6</td><td>Hafsat Abdullahi</td><td>100</td><td>Member</td></tr>
          </tbody>
        </table>
        <p style="margin-top:14px; font-size:13px; color:rgba(250,246,238,0.4);">
          Signed: <strong style="color:var(--gold-lt)">Abubakar Umar</strong> — President (2017/2018) &nbsp;|&nbsp;
          <strong style="color:var(--gold-lt)">Adamu Umar</strong> — Sec. Gen (2017/2018)
        </p>
      `
    },
  ];

  document.addEventListener('DOMContentLoaded', () => {
    /* Build TOC */
    document.getElementById('tocGrid').innerHTML = CONSTITUTION.map((a, i) => `
      <button class="toc-item" onclick="openArticle(${i})">
        <span class="toc-num">${a.num}</span>
        <span>${a.title}</span>
      </button>
    `).join('');

    /* Build accordion */
    document.getElementById('accordionContainer').innerHTML = CONSTITUTION.map((a, i) => `
      <div class="accordion-item" id="acc-${i}">
        <button class="accordion-trigger" onclick="toggleArticle(${i})">
          <span class="acc-num">${a.num}</span>
          <span class="acc-title">${a.title}</span>
          <svg class="acc-chevron" viewBox="0 0 24 24" fill="none" stroke="#c9953a" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="m19.5 8.25-7.5 7.5-7.5-7.5"/></svg>
        </button>
        <div class="accordion-body">${a.content}</div>
      </div>
    `).join('');

    const hash = window.location.hash.replace('#sec-', '');
    if (hash && !isNaN(parseInt(hash))) openArticle(parseInt(hash));
  });

  function toggleArticle(i) {
    const item   = document.getElementById('acc-' + i);
    const isOpen = item.classList.contains('open');
    document.querySelectorAll('.accordion-item').forEach(el => el.classList.remove('open'));
    if (!isOpen) {
      item.classList.add('open');
      setTimeout(() => item.scrollIntoView({ behavior: 'smooth', block: 'nearest' }), 100);
    }
  }

  function openArticle(i) {
    document.querySelectorAll('.accordion-item').forEach(el => el.classList.remove('open'));
    const item = document.getElementById('acc-' + i);
    if (item) {
      item.classList.add('open');
      setTimeout(() => item.scrollIntoView({ behavior: 'smooth', block: 'start' }), 100);
    }
  }
